"""add user analytics table

Revision ID: 04bb5d2c9526
Revises: 3624511569a4
Create Date: 2025-01-24 21:56:05.151990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bb5d2c9526'
down_revision: Union[str, None] = '3624511569a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_links_saved', sa.Integer(), nullable=True),
    sa.Column('active_days_count', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('manual_reminder_count', sa.Integer(), nullable=True),
    sa.Column('default_reminder_count', sa.Integer(), nullable=True),
    sa.Column('total_snoozes', sa.Integer(), nullable=True),
    sa.Column('completed_reminders', sa.Integer(), nullable=True),
    sa.Column('missed_reminders', sa.Integer(), nullable=True),
    sa.Column('reminder_completion_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_analytics')
    # ### end Alembic commands ###
