"""update user analytics columns

Revision ID: 5285688e548e
Revises: 04bb5d2c9526
Create Date: 2025-01-24 22:26:05.815347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5285688e548e'
down_revision: Union[str, None] = '04bb5d2c9526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_analytics', sa.Column('default_passive_count', sa.Integer(), nullable=True))
    op.add_column('user_analytics', sa.Column('active_skip_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_analytics', 'active_skip_count')
    op.drop_column('user_analytics', 'default_passive_count')
    # ### end Alembic commands ###
