"""update_link_model_constraints

Revision ID: 744479e59312
Revises: 5285688e548e
Create Date: 2025-01-29 21:02:36.706335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744479e59312'
down_revision: Union[str, None] = '5285688e548e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2083),
               existing_nullable=False)
    op.create_index('idx_links_user_created', 'links', ['user_id', 'created_at'], unique=False)
    op.drop_constraint('links_user_id_fkey', 'links', type_='foreignkey')
    op.create_foreign_key(None, 'links', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('links', 'content_type')
    op.drop_column('links', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('links', sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.create_foreign_key('links_user_id_fkey', 'links', 'users', ['user_id'], ['id'])
    op.drop_index('idx_links_user_created', table_name='links')
    op.alter_column('links', 'url',
               existing_type=sa.String(length=2083),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
